title: AI Conference Deadlines # (Maintained by @abhshkdz)
# email: abhshkdz@vt.edu
description: Countdowns to top CV/NLP/ML/Robotics/AI conference deadlines
author: Abhishek Das

domain: "shilinhe.github.io/conferences/"
baseurl: ""

twitter_username: abhshkdz
twitter_hashtag: machinelearning
github_username: ShilinHe
github_repo: conferences

markdown: kramdown
ga_id: UA-36274081-2
